# Generated by Django 5.0.7 on 2024-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0007_incentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='job')),
                ('title', models.CharField(max_length=105)),
                ('point', models.TextField()),
            ],
        ),
    ]
