# Generated by Django 5.0.7 on 2024-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0009_customuser_age_customuser_clg_name_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
