# Generated by Django 5.0.7 on 2024-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0012_customuser_student_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_conformation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
