# Generated by Django 5.0.7 on 2024-08-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0016_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_meterial',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video_meterial',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
