# Generated by Django 5.0.7 on 2024-08-03 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0020_question_paper_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_paper',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='question_paper',
            name='student_score',
        ),
        migrations.RemoveField(
            model_name='question_paper',
            name='test_id',
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('student_score', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
