# Generated by Django 5.0.7 on 2024-08-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0024_score_tot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
