# Generated by Django 5.0.7 on 2024-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0027_category_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_meterial',
            name='subject',
            field=models.CharField(default='exit', max_length=105),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_meterial',
            name='subject',
            field=models.CharField(default='exit', max_length=105),
            preserve_default=False,
        ),
    ]
