# Generated by Django 5.0.7 on 2024-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0011_customuser_gender_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_guid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
