# Generated by Django 5.0.7 on 2024-08-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0013_customuser_student_conformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
