# Generated by Django 5.0.7 on 2024-08-02 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0018_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('obtionA', models.CharField(blank=True, max_length=50, null=True)),
                ('obtionB', models.CharField(blank=True, max_length=50, null=True)),
                ('obtionC', models.CharField(blank=True, max_length=50, null=True)),
                ('obtionD', models.CharField(blank=True, max_length=50, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('student_score', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
