# Generated by Django 5.0.7 on 2024-08-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0019_question_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_paper',
            name='test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
