# Generated by Django 5.0.7 on 2024-08-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0021_remove_question_paper_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_paper',
            name='test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
