# Generated by Django 5.0.7 on 2024-08-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0022_question_paper_test_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='worng_ans',
        ),
    ]
