# Generated by Django 4.0 on 2024-10-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0028_study_meterial_subject_video_meterial_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_meterial',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video_meterial',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='onlineapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.customuser')),
            ],
        ),
    ]
